import Foundation

// MARK: - 40 handcrafted missions (5 regions x 8)

enum MissionCatalog {

    private static func m(
        _ region: Int, _ index: Int, _ name: String, _ intro: String,
        obj: ObjectiveKind, bonus: BonusKind, map: [String],
        enemies: [(EnemyKind, Int, Int)],
        structures: [(StructureKind, Int, Int)] = [],
        spawns: [(Int, Int)],
        exit: (Int, Int)? = nil
    ) -> MissionDef {
        var limit: Int? = nil
        if case .survive(let t) = obj { limit = t }
        return MissionDef(
            id: region * 100 + index, region: region, index: index,
            name: name, intro: intro, objective: obj, bonus: bonus, map: map,
            enemies: enemies.map { ($0.0, Coord(x: $0.1, y: $0.2)) },
            structures: structures.map { ($0.0, Coord(x: $0.1, y: $0.2)) },
            playerSpawns: spawns.map { Coord(x: $0.0, y: $0.1) },
            exitCell: exit.map { Coord(x: $0.0, y: $0.1) },
            turnLimit: limit
        )
    }

    static let all: [MissionDef] = region0 + region1 + region2 + region3 + region4

    static func mission(id: Int) -> MissionDef? { all.first { $0.id == id } }

    static func missions(inRegion r: Int) -> [MissionDef] { all.filter { $0.region == r } }

    // MARK: Region 0 — Rustyard Outskirts

    private static let region0: [MissionDef] = [
        m(0, 0, "First Sparks",
          "Scrap vermin have crossed the boundary ditch. Show them why the Vanguard still patrols.",
          obj: .defeatAll, bonus: .finishUnder(turns: 5),
          map: ["........",
                "........",
                "...P....",
                "........",
                "....P...",
                "........",
                "........",
                "........"],
          enemies: [(.scrapCrawler, 2, 2), (.scrapCrawler, 5, 2), (.boltSpitter, 4, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(0, 1, "Oil Slick Alley",
          "The old lubricant depot leaks across the alley. One spark would make this very brief.",
          obj: .defeatAll, bonus: .hazardKills(1),
          map: ["........",
                "..O..O..",
                ".OOO.OO.",
                "..O..O..",
                "........",
                "........",
                "........",
                "........"],
          enemies: [(.scrapCrawler, 1, 1), (.scrapCrawler, 4, 2), (.scrapCrawler, 6, 3), (.boltSpitter, 3, 0)],
          spawns: [(1, 7), (3, 7), (5, 7)]),

        m(0, 2, "The Watchpost",
          "The watchpost boiler heats half the settlement. The horde would love to put it out permanently.",
          obj: .protectStructure, bonus: .finishUnder(turns: 6),
          map: ["........",
                "...P....",
                "........",
                "........",
                "....P...",
                "........",
                "........",
                "........"],
          enemies: [(.scrapCrawler, 1, 0), (.scrapCrawler, 6, 0), (.scrapCrawler, 4, 2), (.boltSpitter, 2, 1)],
          structures: [(.boiler, 3, 5)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(0, 3, "Rust Procession",
          "A supply crawler hauls the month's coal north. Walk it past the pits and the things that wait in them.",
          obj: .escort, bonus: .finishUnder(turns: 8),
          map: [".....P..",
                "........",
                "..P.....",
                "........",
                "....P...",
                ".P......",
                "........",
                "........"],
          enemies: [(.scrapCrawler, 3, 1), (.boltSpitter, 5, 2), (.scrapCrawler, 6, 3), (.scrapCrawler, 2, 4)],
          structures: [(.convoy, 1, 6)],
          spawns: [(2, 7), (4, 7), (6, 7)],
          exit: (6, 0)),

        m(0, 4, "Pit Row",
          "Subsidence turned the storage yard into a grid of open shafts. Use the architecture.",
          obj: .defeatAll, bonus: .hazardKills(2),
          map: ["........",
                "..P..P..",
                "PP....PP",
                "........",
                "...PP...",
                "........",
                "........",
                "........"],
          enemies: [(.ironHusk, 4, 1), (.scrapCrawler, 2, 3), (.scrapCrawler, 5, 3), (.boltSpitter, 3, 0)],
          spawns: [(1, 6), (4, 6), (6, 6)]),

        m(0, 5, "Smelter Cores",
          "Two rogue foundry cores feed the Rustyard swarm. Crack them open and the assembly lines starve.",
          obj: .destroyTargets, bonus: .finishUnder(turns: 6),
          map: ["........",
                "........",
                "...PP...",
                "........",
                "........",
                "..P..P..",
                "........",
                "........"],
          enemies: [(.ironHusk, 1, 2), (.boltSpitter, 3, 3), (.boltSpitter, 6, 2)],
          structures: [(.foundryCore, 2, 1), (.foundryCore, 5, 1)],
          spawns: [(2, 7), (4, 7), (6, 7)]),

        m(0, 6, "Hold the Line",
          "A spawner kiln rolled up to the ditch overnight. Reinforcements arrive in six turns. Stand.",
          obj: .survive(turns: 6), bonus: .hazardKills(1),
          map: ["........",
                "........",
                "..O.O...",
                ".O...O..",
                "........",
                "........",
                "........",
                "........"],
          enemies: [(.foundrySpawner, 4, 0), (.scrapCrawler, 1, 1), (.scrapCrawler, 6, 1), (.boltSpitter, 3, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(0, 7, "The Foundry King",
          "The first overseer waits in the slag court, crowned and furious. End the Rustyard's siege.",
          obj: .defeatAll, bonus: .finishUnder(turns: 8),
          map: ["...PP...",
                "........",
                "........",
                "..O..O..",
                "........",
                "...PP...",
                "........",
                "........"],
          enemies: [(.foundryKing, 4, 1), (.scrapCrawler, 2, 2), (.scrapCrawler, 6, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),
    ]

    // MARK: Region 1 — The Steamworks

    private static let region1: [MissionDef] = [
        m(1, 0, "Pressure Test",
          "The vent floor scalds anything that lingers. The Tyrant's ticks don't intend to linger.",
          obj: .defeatAll, bonus: .noDamage,
          map: ["........",
                "..V..V..",
                "........",
                ".V....V.",
                "........",
                "..V..V..",
                "........",
                "........"],
          enemies: [(.boilerTick, 3, 0), (.boilerTick, 6, 1), (.scrapCrawler, 1, 2), (.scrapCrawler, 5, 0)],
          spawns: [(2, 7), (4, 7), (6, 7)]),

        m(1, 1, "The Belt Run",
          "Three freight belts still run at full speed, and two of them end in open shafts. Mind the footing.",
          obj: .defeatAll, bonus: .hazardKills(1),
          map: ["........",
                ">>>>>>>P",
                "........",
                "P<<<<<<<",
                "........",
                ">>>>>>>P",
                "........",
                "........"],
          enemies: [(.springLeaper, 4, 0), (.scrapCrawler, 2, 2), (.boltSpitter, 6, 2), (.scrapCrawler, 5, 4)],
          spawns: [(1, 7), (3, 7), (6, 7)]),

        m(1, 2, "Scald Ward",
          "The ward boiler keeps the infirmary warm. The Tyrant sent a repair crew of the wrong kind.",
          obj: .protectStructure, bonus: .finishUnder(turns: 7),
          map: ["........",
                ".V....V.",
                "........",
                "..VV....",
                "........",
                "......V.",
                "........",
                "........"],
          enemies: [(.boltSpitter, 2, 0), (.boltSpitter, 5, 1), (.boilerTick, 4, 1), (.cogMender, 3, 0)],
          structures: [(.boiler, 4, 5)],
          spawns: [(1, 6), (3, 7), (6, 6)]),

        m(1, 3, "Steam Convoy",
          "Ride the north belts. The crawler carries valve seals the whole district needs.",
          obj: .escort, bonus: .finishUnder(turns: 8),
          map: ["........",
                "..^..^..",
                "..^..^..",
                "..^..^..",
                "........",
                ".>>..<<.",
                "........",
                "........"],
          enemies: [(.springLeaper, 1, 1), (.scrapCrawler, 0, 2), (.scrapCrawler, 6, 3), (.boltSpitter, 7, 1)],
          structures: [(.convoy, 3, 7)],
          spawns: [(1, 7), (5, 7), (6, 7)],
          exit: (4, 0)),

        m(1, 4, "Mender's Round",
          "Two menders patch the patrol faster than you can dent it. Schedule their retirement first.",
          obj: .defeatAll, bonus: .finishUnder(turns: 7),
          map: ["........",
                "...VV...",
                ".O....O.",
                "........",
                ".O....O.",
                "...VV...",
                "........",
                "........"],
          enemies: [(.cogMender, 1, 0), (.cogMender, 6, 0), (.ironHusk, 4, 2), (.scrapCrawler, 2, 1), (.scrapCrawler, 5, 3)],
          spawns: [(2, 7), (4, 7), (6, 7)]),

        m(1, 5, "Valve Cores",
          "Two pressure cores overdrive the district's vents. Crack them before the floor cooks.",
          obj: .destroyTargets, bonus: .hazardKills(1),
          map: ["........",
                "........",
                "..V..V..",
                "........",
                ".O....O.",
                "........",
                "........",
                "........"],
          enemies: [(.boilerTick, 3, 2), (.boilerTick, 4, 0), (.boltSpitter, 4, 3)],
          structures: [(.foundryCore, 1, 1), (.foundryCore, 6, 1)],
          spawns: [(2, 7), (4, 7), (6, 7)]),

        m(1, 6, "Boiler Floor",
          "The kiln walked itself onto the boiler floor and started production. Survive its quota.",
          obj: .survive(turns: 7), bonus: .hazardKills(2),
          map: ["........",
                "........",
                "..O..O..",
                ".V....V.",
                "........",
                "..O..O..",
                "........",
                "........"],
          enemies: [(.foundrySpawner, 3, 0), (.boilerTick, 6, 1), (.springLeaper, 1, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(1, 7, "Vapor Tyrant",
          "Every valve in the district whistles its name. Silence the Steamworks' tyrant.",
          obj: .defeatAll, bonus: .finishUnder(turns: 9),
          map: ["........",
                ".V....V.",
                "........",
                "...WW...",
                "........",
                ".V....V.",
                "........",
                "........"],
          enemies: [(.vaporTyrant, 4, 1), (.boilerTick, 1, 2), (.cogMender, 6, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),
    ]

    // MARK: Region 2 — Gearspine Mines

    private static let region2: [MissionDef] = [
        m(2, 0, "Thin Floor",
          "The upper gallery floor is one bad step from being a ceiling. Let the enemy take that step.",
          obj: .defeatAll, bonus: .hazardKills(1),
          map: ["........",
                "..CCCC..",
                ".CC..CC.",
                "..C..C..",
                ".CCCCCC.",
                "........",
                "........",
                "........"],
          enemies: [(.scrapCrawler, 3, 0), (.scrapCrawler, 5, 0), (.scrapCrawler, 2, 1), (.ironHusk, 4, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 1, "What Tunnels Below",
          "Something reads your footsteps through the rock. Keep moving or be read.",
          obj: .defeatAll, bonus: .noDamage,
          map: ["...P....",
                "........",
                "......P.",
                "........",
                ".P......",
                "........",
                "........",
                "........"],
          enemies: [(.rustBurrower, 4, 3), (.boltSpitter, 2, 1), (.boltSpitter, 5, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 2, "Prop the Shaft",
          "The shaft boiler drives the only working lift. Lose it and the miners walk home through THEM.",
          obj: .protectStructure, bonus: .finishUnder(turns: 7),
          map: ["........",
                "..C..C..",
                ".CC..CC.",
                "........",
                "...CC...",
                "........",
                "........",
                "........"],
          enemies: [(.gearSplitter, 4, 1), (.scrapCrawler, 1, 0), (.scrapCrawler, 6, 0)],
          structures: [(.boiler, 4, 5)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 3, "Ore Cart Escort",
          "One cart of chrono-ore, bound for the surface. Half the mine wants it back.",
          obj: .escort, bonus: .finishUnder(turns: 9),
          map: ["........",
                "..P..P..",
                "........",
                ".C.CC.C.",
                "........",
                "..P..P..",
                "........",
                "........"],
          enemies: [(.rustBurrower, 3, 2), (.scrapCrawler, 2, 0), (.scrapCrawler, 5, 2), (.boltSpitter, 6, 2)],
          structures: [(.convoy, 4, 7)],
          spawns: [(2, 7), (6, 7), (1, 6)],
          exit: (4, 0)),

        m(2, 4, "Split Seams",
          "The redundancy engines patrol in pairs that become quartets. Do the arithmetic with your fists.",
          obj: .defeatAll, bonus: .finishUnder(turns: 8),
          map: ["........",
                "........",
                "...PP...",
                "........",
                ".C....C.",
                "........",
                "........",
                "........"],
          enemies: [(.gearSplitter, 2, 1), (.gearSplitter, 5, 1), (.ironHusk, 4, 3)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 5, "Dynamo Cores",
          "Three dynamo cores light the deep galleries for the horde. Put the deep back to sleep.",
          obj: .destroyTargets, bonus: .hazardKills(2),
          map: ["........",
                "........",
                "..P..P..",
                "........",
                ".C.CC.C.",
                "........",
                "........",
                "........"],
          enemies: [(.boltSpitter, 3, 1), (.ironHusk, 5, 3), (.scrapCrawler, 2, 3)],
          structures: [(.foundryCore, 1, 1), (.foundryCore, 4, 0), (.foundryCore, 6, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 6, "Cave-In",
          "Two kilns, a burrower, and a floor made of promises. Hold until the charges are set.",
          obj: .survive(turns: 7), bonus: .hazardKills(2),
          map: ["........",
                "..CCCC..",
                "..C..C..",
                ".CC..CC.",
                "..CCCC..",
                "........",
                "........",
                "........"],
          enemies: [(.foundrySpawner, 1, 0), (.foundrySpawner, 6, 0), (.rustBurrower, 4, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(2, 7, "Cog Colossus",
          "The mountain's heartbeat has a body, and it has noticed the lights. Bring it down.",
          obj: .defeatAll, bonus: .finishUnder(turns: 10),
          map: ["...PP...",
                "........",
                "........",
                "..C..C..",
                "........",
                "..P..P..",
                "........",
                "........"],
          enemies: [(.cogColossus, 4, 1), (.scrapCrawler, 1, 2), (.scrapCrawler, 6, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),
    ]

    // MARK: Region 3 — Patina Bastion

    private static let region3: [MissionDef] = [
        m(3, 0, "Green Walls",
          "The Bastion garrison still drills on schedule. Today's exercise: you.",
          obj: .defeatAll, bonus: .finishUnder(turns: 7),
          map: ["........",
                ".W....W.",
                "........",
                "...OO...",
                "........",
                ".W....W.",
                "........",
                "........"],
          enemies: [(.aegisPlate, 4, 1), (.boltSpitter, 2, 2), (.boltSpitter, 6, 2), (.scrapCrawler, 3, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 1, "Snare Court",
          "Razor filament glitters between the colonnades. Whatever stops moving here stays.",
          obj: .defeatAll, bonus: .noDamage,
          map: ["........",
                "........",
                "..P..P..",
                "........",
                "....W...",
                "........",
                "........",
                "........"],
          enemies: [(.wireSpinner, 2, 1), (.wireSpinner, 5, 1), (.scrapCrawler, 3, 2), (.scrapCrawler, 6, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 2, "Garrison Boiler",
          "The captured garrison boiler feeds your forward camp. The Bastion wants its property back, in pieces.",
          obj: .protectStructure, bonus: .finishUnder(turns: 8),
          map: ["........",
                "........",
                ".O....O.",
                "........",
                "..W..W..",
                "........",
                "........",
                "........"],
          enemies: [(.mortarHulk, 4, 0), (.aegisPlate, 2, 1), (.scrapCrawler, 6, 1)],
          structures: [(.boiler, 3, 5)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 3, "Moat Crossing",
          "The old moat is shallow enough to wade and wide enough to die in. The crawler goes first.",
          obj: .escort, bonus: .finishUnder(turns: 9),
          map: ["........",
                "........",
                ".WWWWWW.",
                "WW....WW",
                ".W....W.",
                "........",
                "........",
                "........"],
          enemies: [(.beamSentry, 1, 1), (.wireSpinner, 6, 3), (.scrapCrawler, 3, 2)],
          structures: [(.convoy, 3, 7)],
          spawns: [(1, 7), (5, 7), (6, 7)],
          exit: (4, 0)),

        m(3, 4, "Suppressing Fire",
          "Two mortar emplacements rake the approach. The marks on the ground are promises; don't stand in them.",
          obj: .defeatAll, bonus: .hazardKills(1),
          map: ["........",
                "........",
                "..O..O..",
                "...PP...",
                "..O..O..",
                "........",
                "........",
                "........"],
          enemies: [(.mortarHulk, 1, 0), (.mortarHulk, 6, 0), (.ironHusk, 4, 2), (.wireSpinner, 3, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 5, "Bastion Cores",
          "Three shield cores keep the inner wall humming. Drop them and the Bastion finally sleeps.",
          obj: .destroyTargets, bonus: .finishUnder(turns: 8),
          map: ["........",
                "........",
                "...WW...",
                ".O....O.",
                "........",
                "...PP...",
                "........",
                "........"],
          enemies: [(.beamSentry, 0, 0), (.aegisPlate, 3, 1), (.aegisPlate, 6, 2)],
          structures: [(.foundryCore, 1, 1), (.foundryCore, 4, 1), (.foundryCore, 6, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 6, "Siege Night",
          "The garrison attacks at moonrise, by the book. The book is eighty years old. Survive chapter one.",
          obj: .survive(turns: 8), bonus: .hazardKills(2),
          map: ["........",
                "........",
                ".V....V.",
                "...OO...",
                "........",
                ".P....P.",
                "........",
                "........"],
          enemies: [(.foundrySpawner, 4, 0), (.mortarHulk, 1, 1), (.wireSpinner, 6, 1), (.scrapCrawler, 2, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(3, 7, "The King Rebuilt",
          "The Bastion's armories restored the Foundry King with parade plating. He remembers you.",
          obj: .defeatAll, bonus: .hazardKills(1),
          map: ["...PP...",
                "........",
                "........",
                ".O.WW.O.",
                "........",
                "..P..P..",
                "........",
                "........"],
          enemies: [(.foundryKing, 4, 1), (.aegisPlate, 2, 2), (.cogMender, 6, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),
    ]

    // MARK: Region 4 — The Chronoforge

    private static let region4: [MissionDef] = [
        m(4, 0, "Hands of the Clock",
          "The Archon's drones move on the second, every second. Be the grit in the gears.",
          obj: .defeatAll, bonus: .finishUnder(turns: 6),
          map: ["........",
                "........",
                "...PP...",
                ".C....C.",
                "........",
                "...VV...",
                "........",
                "........"],
          enemies: [(.clockDrone, 1, 1), (.clockDrone, 6, 1), (.clockDrone, 2, 2), (.clockDrone, 5, 2)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(4, 1, "Oil and Water",
          "The forge floor is slick with fuel and cut by coolant channels. Fight chemistry with positioning.",
          obj: .defeatAll, bonus: .hazardKills(2),
          map: ["........",
                "..O..O..",
                ".OWOOWO.",
                "..O..O..",
                "........",
                "...WW...",
                "........",
                "........"],
          enemies: [(.boilerTick, 1, 0), (.boilerTick, 6, 0), (.ironHusk, 4, 1), (.wireSpinner, 3, 0)],
          spawns: [(2, 7), (4, 7), (6, 7)]),

        m(4, 2, "Mainspring Guard",
          "Your engineers tapped a mainspring housing for power. The Archon calls that theft. Hold the claim.",
          obj: .protectStructure, bonus: .finishUnder(turns: 8),
          map: ["........",
                "........",
                ".P....P.",
                "...CC...",
                "........",
                "........",
                "........",
                "........"],
          enemies: [(.clockDrone, 2, 1), (.clockDrone, 5, 1), (.mortarHulk, 4, 0), (.cogMender, 3, 0)],
          structures: [(.boiler, 4, 5)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(4, 3, "The Last Shipment",
          "One crawler of stolen mainspring steel decides the campaign. The forge knows it left.",
          obj: .escort, bonus: .finishUnder(turns: 9),
          map: ["........",
                "...PP...",
                "........",
                ".C....C.",
                "..O..O..",
                "........",
                "........",
                "........"],
          enemies: [(.springLeaper, 2, 1), (.rustBurrower, 5, 3), (.clockDrone, 6, 1), (.clockDrone, 1, 2)],
          structures: [(.convoy, 4, 7)],
          spawns: [(2, 7), (6, 7), (1, 6)],
          exit: (4, 0)),

        m(4, 4, "Full Assembly",
          "Every pattern the uprising ever built walks this floor. Consider it a museum. Close it.",
          obj: .defeatAll, bonus: .noDamage,
          map: ["........",
                "........",
                "..V..V..",
                "...WW...",
                "..O..O..",
                "........",
                "........",
                "........"],
          enemies: [(.gearSplitter, 2, 1), (.aegisPlate, 5, 1), (.cogMender, 4, 0), (.boltSpitter, 1, 0), (.boltSpitter, 6, 0)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(4, 5, "Regulator Cores",
          "Three regulator cores keep the Archon's timetable true. Introduce some slippage.",
          obj: .destroyTargets, bonus: .finishUnder(turns: 9),
          map: ["........",
                "........",
                "........",
                "..P..P..",
                ".>>..<<.",
                "........",
                "........",
                "........"],
          enemies: [(.beamSentry, 0, 2), (.beamSentry, 7, 2), (.clockDrone, 3, 2), (.clockDrone, 4, 2)],
          structures: [(.foundryCore, 1, 1), (.foundryCore, 6, 1), (.foundryCore, 4, 0)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(4, 6, "Zero Hour",
          "At zero hour the forge doors open and do not close. Survive what files out.",
          obj: .survive(turns: 8), bonus: .hazardKills(2),
          map: ["........",
                "........",
                "..O.O...",
                ".V....V.",
                "...OO...",
                "........",
                "........",
                "........"],
          enemies: [(.foundrySpawner, 1, 0), (.foundrySpawner, 6, 0), (.clockDrone, 4, 1), (.mortarHulk, 3, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),

        m(4, 7, "Chrono Archon",
          "The Archon waits beside the great escapement, holding the war's last schedule. Tear out the page.",
          obj: .defeatAll, bonus: .finishUnder(turns: 12),
          map: ["...PP...",
                "........",
                "........",
                ".O....O.",
                "..WCCW..",
                "........",
                "........",
                "........"],
          enemies: [(.chronoArchon, 4, 1), (.clockDrone, 1, 2), (.clockDrone, 6, 2), (.cogMender, 5, 1)],
          spawns: [(2, 6), (4, 6), (6, 6)]),
    ]
}
